/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista1;

import java.awt.Color;

/**
 *
 * @author User
 */
public class AgregarLibroNuevo extends javax.swing.JFrame {

    /**
     * Creates new form AgregarLibroNuevo
     */
    public AgregarLibroNuevo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtStockLibroNuevo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtTituloLibroNuevo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtPrecioLibroNuevo = new javax.swing.JTextField();
        jbtnLimpiarLibroNuevo = new javax.swing.JButton();
        jbtnAgregarLibroNuevo = new javax.swing.JButton();
        jcbxEditorialesLibroNuevo = new javax.swing.JComboBox<>();
        jcbxAutoresLibroNuevo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jcbxTipoLN = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jtxtNumpagLN = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Libro Nuevo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Agregar Nuevo Libro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Autor del Libro:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Editorial:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Stock:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jtxtStockLibroNuevo.setForeground(new java.awt.Color(153, 153, 153));
        jtxtStockLibroNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtStockLibroNuevoMousePressed(evt);
            }
        });
        jPanel1.add(jtxtStockLibroNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 140, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Título del Libro:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jtxtTituloLibroNuevo.setForeground(new java.awt.Color(153, 153, 153));
        jtxtTituloLibroNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtTituloLibroNuevoMousePressed(evt);
            }
        });
        jPanel1.add(jtxtTituloLibroNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 140, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Precio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        jPanel1.add(jtxtPrecioLibroNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 140, 40));

        jbtnLimpiarLibroNuevo.setBackground(new java.awt.Color(255, 51, 51));
        jbtnLimpiarLibroNuevo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jbtnLimpiarLibroNuevo.setText("Limpiar");
        jPanel1.add(jbtnLimpiarLibroNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 140, 50));

        jbtnAgregarLibroNuevo.setBackground(new java.awt.Color(51, 153, 255));
        jbtnAgregarLibroNuevo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jbtnAgregarLibroNuevo.setText("Agregar");
        jPanel1.add(jbtnAgregarLibroNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 190, 60));

        jPanel1.add(jcbxEditorialesLibroNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 140, 40));

        jPanel1.add(jcbxAutoresLibroNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 140, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tipo de Libro:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jPanel1.add(jcbxTipoLN, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 140, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("N° de Páginas:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        jPanel1.add(jtxtNumpagLN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtTituloLibroNuevoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtTituloLibroNuevoMousePressed
        
    }//GEN-LAST:event_jtxtTituloLibroNuevoMousePressed

    private void jtxtStockLibroNuevoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtStockLibroNuevoMousePressed
        
    }//GEN-LAST:event_jtxtStockLibroNuevoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarLibroNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarLibroNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarLibroNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarLibroNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarLibroNuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbtnAgregarLibroNuevo;
    public javax.swing.JButton jbtnLimpiarLibroNuevo;
    public javax.swing.JComboBox<String> jcbxAutoresLibroNuevo;
    public javax.swing.JComboBox<String> jcbxEditorialesLibroNuevo;
    public javax.swing.JComboBox<String> jcbxTipoLN;
    public javax.swing.JTextField jtxtNumpagLN;
    public javax.swing.JTextField jtxtPrecioLibroNuevo;
    public javax.swing.JTextField jtxtStockLibroNuevo;
    public javax.swing.JTextField jtxtTituloLibroNuevo;
    // End of variables declaration//GEN-END:variables
}
