/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista1;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AgregarLibroExis extends javax.swing.JFrame {

    /**
     * Creates new form AgregarLibroExis
     */
    public AgregarLibroExis() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jbtnBuscarLibroExistente = new javax.swing.JButton();
        jbtnLimpiarLibroExistente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnAgregarLibroExistente = new javax.swing.JButton();
        jcbxEditorialLibroExistente = new javax.swing.JComboBox<>();
        jcbxAutorLibroExistente = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jtxtTituloLibroExistente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcbxTipoLE = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jtxtNumpagLE = new javax.swing.JTextField();
        jspncantidadlibro = new javax.swing.JSpinner();
        jspncodigolibro = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Libro Existente");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Añadir Libro Existente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Título del Libro:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Autor del Libro:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jbtnBuscarLibroExistente.setBackground(new java.awt.Color(255, 153, 51));
        jbtnBuscarLibroExistente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnBuscarLibroExistente.setForeground(new java.awt.Color(153, 153, 153));
        jbtnBuscarLibroExistente.setText("Buscar");
        jPanel1.add(jbtnBuscarLibroExistente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 140, 50));

        jbtnLimpiarLibroExistente.setBackground(new java.awt.Color(255, 51, 51));
        jbtnLimpiarLibroExistente.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jbtnLimpiarLibroExistente.setText("Limpiar");
        jPanel1.add(jbtnLimpiarLibroExistente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 140, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Cantidad de libros:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Editorial:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jbtnAgregarLibroExistente.setBackground(new java.awt.Color(51, 153, 255));
        jbtnAgregarLibroExistente.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jbtnAgregarLibroExistente.setText("Agregar");
        jPanel1.add(jbtnAgregarLibroExistente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 140, 60));

        jcbxEditorialLibroExistente.setEnabled(false);
        jPanel1.add(jcbxEditorialLibroExistente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 140, 40));

        jcbxAutorLibroExistente.setEnabled(false);
        jPanel1.add(jcbxAutorLibroExistente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 140, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Codigo del Libro:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jtxtTituloLibroExistente.setEditable(false);
        jPanel1.add(jtxtTituloLibroExistente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 140, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Tipo de Libro:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        jcbxTipoLE.setEnabled(false);
        jPanel1.add(jcbxTipoLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 140, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("N° de Páginas:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jtxtNumpagLE.setEnabled(false);
        jPanel1.add(jtxtNumpagLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 140, 40));
        jPanel1.add(jspncantidadlibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 140, 40));
        jPanel1.add(jspncodigolibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 440));
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarLibroExis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarLibroExis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarLibroExis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarLibroExis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarLibroExis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbtnAgregarLibroExistente;
    public javax.swing.JButton jbtnBuscarLibroExistente;
    public javax.swing.JButton jbtnLimpiarLibroExistente;
    public javax.swing.JComboBox<String> jcbxAutorLibroExistente;
    public javax.swing.JComboBox<String> jcbxEditorialLibroExistente;
    public javax.swing.JComboBox<String> jcbxTipoLE;
    public javax.swing.JSpinner jspncantidadlibro;
    public javax.swing.JSpinner jspncodigolibro;
    public javax.swing.JTextField jtxtNumpagLE;
    public javax.swing.JTextField jtxtTituloLibroExistente;
    // End of variables declaration//GEN-END:variables
}
