/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista1;


import java.awt.Color;

/**
 *
 * @author admin
 */
public class AñadirEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form AñadirUsuarios
     */
    public AñadirEmpleados() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtApellidos = new javax.swing.JTextField();
        jtxtNumeroCelular = new javax.swing.JTextField();
        jdtcFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jcbxGenero = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jbtnRegistrar = new javax.swing.JButton();
        jtxtNombres = new javax.swing.JTextField();
        jcbxTipoEmpleado = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jpswConfirmarContraseña = new javax.swing.JPasswordField();
        jpswIngresarContraseña = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtCorreo = new javax.swing.JTextField();
        jtxtDNI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Nuevo Empleado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(320, 490));
        jPanel1.setMinimumSize(new java.awt.Dimension(320, 490));
        jPanel1.setPreferredSize(new java.awt.Dimension(320, 490));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtApellidos.setForeground(new java.awt.Color(153, 153, 153));
        jtxtApellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtApellidosMousePressed(evt);
            }
        });
        jtxtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtApellidosActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, 40));

        jtxtNumeroCelular.setForeground(new java.awt.Color(153, 153, 153));
        jtxtNumeroCelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtNumeroCelularMousePressed(evt);
            }
        });
        jPanel1.add(jtxtNumeroCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 130, 40));

        jdtcFechaNacimiento.setDateFormatString("yyyy-MM-dd");
        jdtcFechaNacimiento.setMaxSelectableDate(new java.util.Date(253370786512000L));
        jdtcFechaNacimiento.setMinSelectableDate(new java.util.Date(-2208966572000L));
        jdtcFechaNacimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jdtcFechaNacimientoMousePressed(evt);
            }
        });
        jPanel1.add(jdtcFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 130, 40));

        jLabel2.setText("Género");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jcbxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMENINO" }));
        jPanel1.add(jcbxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 130, 40));

        jLabel3.setText("Fecha de nacimiento");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jbtnRegistrar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jbtnRegistrar.setText("Registrar");
        jbtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 250, 40));

        jtxtNombres.setForeground(new java.awt.Color(153, 153, 153));
        jtxtNombres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtNombresMousePressed(evt);
            }
        });
        jPanel1.add(jtxtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, 40));

        jcbxTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "EMPLEADO" }));
        jPanel1.add(jcbxTipoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 130, 40));

        jLabel6.setText("Tipo de empleado");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 130, -1));

        jpswConfirmarContraseña.setForeground(new java.awt.Color(153, 153, 153));
        jpswConfirmarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpswConfirmarContraseñaMousePressed(evt);
            }
        });
        jPanel1.add(jpswConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 130, 40));

        jpswIngresarContraseña.setForeground(new java.awt.Color(153, 153, 153));
        jpswIngresarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpswIngresarContraseñaMousePressed(evt);
            }
        });
        jPanel1.add(jpswIngresarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 130, 40));

        jLabel7.setText("Ingresar contaseña");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 130, -1));

        jLabel8.setText("Confirmar contaseña");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 130, -1));

        jtxtCorreo.setForeground(new java.awt.Color(153, 153, 153));
        jtxtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtCorreoMousePressed(evt);
            }
        });
        jPanel1.add(jtxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 130, 40));

        jtxtDNI.setForeground(new java.awt.Color(153, 153, 153));
        jtxtDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtDNIMousePressed(evt);
            }
        });
        jPanel1.add(jtxtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 130, 40));

        jLabel1.setText("Nombres");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 70, -1));

        jLabel5.setText("Apellidos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 70, -1));

        jLabel11.setText("DNI");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 70, -1));

        jLabel9.setText("Número de celular");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, -1));

        jLabel10.setText("Correo Electrónico");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jbtnRegistrarActionPerformed

    private void jtxtNombresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtNombresMousePressed
        
            
    }//GEN-LAST:event_jtxtNombresMousePressed

    private void jtxtApellidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtApellidosMousePressed
        
    }//GEN-LAST:event_jtxtApellidosMousePressed

    private void jtxtNumeroCelularMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtNumeroCelularMousePressed
        
    }//GEN-LAST:event_jtxtNumeroCelularMousePressed

    private void jpswIngresarContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpswIngresarContraseñaMousePressed
        
    }//GEN-LAST:event_jpswIngresarContraseñaMousePressed

    private void jpswConfirmarContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpswConfirmarContraseñaMousePressed
        
    }//GEN-LAST:event_jpswConfirmarContraseñaMousePressed

    private void jtxtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtApellidosActionPerformed

    private void jdtcFechaNacimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdtcFechaNacimientoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdtcFechaNacimientoMousePressed

    private void jtxtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCorreoMousePressed
        
    }//GEN-LAST:event_jtxtCorreoMousePressed

    private void jtxtDNIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtDNIMousePressed
        
    }//GEN-LAST:event_jtxtDNIMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbtnRegistrar;
    public javax.swing.JComboBox<String> jcbxGenero;
    public javax.swing.JComboBox<String> jcbxTipoEmpleado;
    public com.toedter.calendar.JDateChooser jdtcFechaNacimiento;
    public javax.swing.JPasswordField jpswConfirmarContraseña;
    public javax.swing.JPasswordField jpswIngresarContraseña;
    public javax.swing.JTextField jtxtApellidos;
    public javax.swing.JTextField jtxtCorreo;
    public javax.swing.JTextField jtxtDNI;
    public javax.swing.JTextField jtxtNombres;
    public javax.swing.JTextField jtxtNumeroCelular;
    // End of variables declaration//GEN-END:variables
}
