/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista1;

/**
 *
 * @author admin
 */
public class ConfirmarCompra extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmarCompra
     */
    public ConfirmarCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnConfirmarCompra = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtxaBorradorRecibo = new javax.swing.JTextArea();
        jbtnCancelarCompra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnConfirmarCompra.setBackground(new java.awt.Color(51, 153, 255));
        jbtnConfirmarCompra.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jbtnConfirmarCompra.setText("Confirmar Compra");
        jPanel1.add(jbtnConfirmarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 190, 40));

        jtxaBorradorRecibo.setEditable(false);
        jtxaBorradorRecibo.setColumns(20);
        jtxaBorradorRecibo.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jtxaBorradorRecibo.setRows(5);
        jtxaBorradorRecibo.setText("RECIBO");
        jScrollPane5.setViewportView(jtxaBorradorRecibo);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 350));

        jbtnCancelarCompra.setBackground(new java.awt.Color(255, 51, 51));
        jbtnCancelarCompra.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jbtnCancelarCompra.setText("Cancelar Compra");
        jPanel1.add(jbtnCancelarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 190, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmarCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JButton jbtnCancelarCompra;
    public javax.swing.JButton jbtnConfirmarCompra;
    public javax.swing.JTextArea jtxaBorradorRecibo;
    // End of variables declaration//GEN-END:variables
}
