/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista1;

/**
 *
 * @author User
 */
public class EditarLibros extends javax.swing.JFrame {

    /**
     * Creates new form AgregarLibroNuevo
     */
    public EditarLibros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtStock_Editar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtTitulo_Editar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtPrecio_Editar = new javax.swing.JTextField();
        jbtnActualizarLibro = new javax.swing.JButton();
        jcbxEditorial_EditarLibros = new javax.swing.JComboBox<>();
        jcbxAutores_EditarLibros = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jtxt_NdePaginas_Editar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcbx_TipoDeLibro_Editar = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Libro Nuevo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Editar Libros", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Autor del Libro:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Editorial:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Stock:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));
        jPanel1.add(jtxtStock_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 140, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Título del Libro:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 100, -1));

        jtxtTitulo_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTitulo_EditarActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtTitulo_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 140, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Precio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        jPanel1.add(jtxtPrecio_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 140, 40));

        jbtnActualizarLibro.setBackground(new java.awt.Color(51, 153, 255));
        jbtnActualizarLibro.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jbtnActualizarLibro.setText("Actualizar");
        jPanel1.add(jbtnActualizarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 200, 60));

        jPanel1.add(jcbxEditorial_EditarLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 140, 40));

        jPanel1.add(jcbxAutores_EditarLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 140, 40));

        jLabel5.setText("N° de Paginas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));
        jPanel1.add(jtxt_NdePaginas_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 140, 40));

        jLabel7.setText("Tipo de Libro:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jPanel1.add(jcbx_TipoDeLibro_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtTitulo_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTitulo_EditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTitulo_EditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarLibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbtnActualizarLibro;
    public javax.swing.JComboBox<String> jcbxAutores_EditarLibros;
    public javax.swing.JComboBox<String> jcbxEditorial_EditarLibros;
    public javax.swing.JComboBox<String> jcbx_TipoDeLibro_Editar;
    public javax.swing.JTextField jtxtPrecio_Editar;
    public javax.swing.JTextField jtxtStock_Editar;
    public javax.swing.JTextField jtxtTitulo_Editar;
    public javax.swing.JTextField jtxt_NdePaginas_Editar;
    // End of variables declaration//GEN-END:variables
}
