/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista1;

import java.awt.Color;

/**
 *
 * @author admin
 */
public class EditarEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form EditarDatosUsuarios
     */
    public EditarEmpleados() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtEditarApellidos = new javax.swing.JTextField();
        jtxtEditarNumCelular = new javax.swing.JTextField();
        jdtcEditarFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jcbxEditarGenero = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbtnActualizarEmpleado = new javax.swing.JButton();
        jtxtEditarNombres = new javax.swing.JTextField();
        jcbxEditarEstadoUsuario = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jpswEditarIngresarContraseña = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jpswEditarConfirmarContraseña = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jcbxEditarTipoEmpleado = new javax.swing.JComboBox<>();
        jtxtEditarCorreo = new javax.swing.JTextField();
        jtxtEditarDNI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar Registro de Empleado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(320, 490));
        jPanel1.setMinimumSize(new java.awt.Dimension(320, 490));
        jPanel1.setPreferredSize(new java.awt.Dimension(320, 490));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtEditarApellidos.setForeground(new java.awt.Color(153, 153, 153));
        jtxtEditarApellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtEditarApellidosMousePressed(evt);
            }
        });
        jPanel1.add(jtxtEditarApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, 40));

        jtxtEditarNumCelular.setForeground(new java.awt.Color(153, 153, 153));
        jtxtEditarNumCelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtEditarNumCelularMousePressed(evt);
            }
        });
        jPanel1.add(jtxtEditarNumCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 130, 40));

        jdtcEditarFechaNacimiento.setDateFormatString("yyyy-MM-dd");
        jdtcEditarFechaNacimiento.setMinSelectableDate(new java.util.Date(-2208966596000L));
        jPanel1.add(jdtcEditarFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 130, 40));

        jLabel2.setText("Género");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jcbxEditarGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMENINO" }));
        jPanel1.add(jcbxEditarGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 130, 40));

        jLabel3.setText("Fecha de nacimiento");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel4.setText("Estado del Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        jbtnActualizarEmpleado.setBackground(new java.awt.Color(51, 153, 255));
        jbtnActualizarEmpleado.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jbtnActualizarEmpleado.setText("Actualizar");
        jbtnActualizarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnActualizarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnActualizarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 130, 50));

        jtxtEditarNombres.setForeground(new java.awt.Color(153, 153, 153));
        jtxtEditarNombres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtEditarNombresMousePressed(evt);
            }
        });
        jPanel1.add(jtxtEditarNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, 40));

        jcbxEditarEstadoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));
        jPanel1.add(jcbxEditarEstadoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 130, 40));

        jLabel7.setText("Ingresar contaseña");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 130, -1));

        jpswEditarIngresarContraseña.setForeground(new java.awt.Color(153, 153, 153));
        jpswEditarIngresarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpswEditarIngresarContraseñaMousePressed(evt);
            }
        });
        jPanel1.add(jpswEditarIngresarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 130, 40));

        jLabel8.setText("Confirmar contaseña");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 130, -1));

        jpswEditarConfirmarContraseña.setForeground(new java.awt.Color(153, 153, 153));
        jpswEditarConfirmarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpswEditarConfirmarContraseñaMousePressed(evt);
            }
        });
        jPanel1.add(jpswEditarConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 130, 40));

        jLabel6.setText("Tipo de empleado");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 130, -1));

        jcbxEditarTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "EMPLEADO" }));
        jPanel1.add(jcbxEditarTipoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 130, 40));

        jtxtEditarCorreo.setForeground(new java.awt.Color(153, 153, 153));
        jtxtEditarCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtEditarCorreoMousePressed(evt);
            }
        });
        jPanel1.add(jtxtEditarCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 130, 40));

        jtxtEditarDNI.setForeground(new java.awt.Color(153, 153, 153));
        jtxtEditarDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtEditarDNIMousePressed(evt);
            }
        });
        jPanel1.add(jtxtEditarDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 130, 40));

        jLabel1.setText("Nombres");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 70, -1));

        jLabel5.setText("Apellidos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 70, -1));

        jLabel9.setText("Número de celular");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, -1));

        jLabel10.setText("Correo Electrónico");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 100, -1));

        jLabel11.setText("DNI");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnActualizarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnActualizarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnActualizarEmpleadoActionPerformed

    private void jtxtEditarNombresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtEditarNombresMousePressed
       
    }//GEN-LAST:event_jtxtEditarNombresMousePressed

    private void jtxtEditarApellidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtEditarApellidosMousePressed
        
    }//GEN-LAST:event_jtxtEditarApellidosMousePressed

    private void jpswEditarIngresarContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpswEditarIngresarContraseñaMousePressed
       
    }//GEN-LAST:event_jpswEditarIngresarContraseñaMousePressed

    private void jpswEditarConfirmarContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpswEditarConfirmarContraseñaMousePressed
        
    }//GEN-LAST:event_jpswEditarConfirmarContraseñaMousePressed

    private void jtxtEditarCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtEditarCorreoMousePressed
       
    }//GEN-LAST:event_jtxtEditarCorreoMousePressed

    private void jtxtEditarDNIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtEditarDNIMousePressed
       
    }//GEN-LAST:event_jtxtEditarDNIMousePressed

    private void jtxtEditarNumCelularMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtEditarNumCelularMousePressed
       
    }//GEN-LAST:event_jtxtEditarNumCelularMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbtnActualizarEmpleado;
    public javax.swing.JComboBox<String> jcbxEditarEstadoUsuario;
    public javax.swing.JComboBox<String> jcbxEditarGenero;
    public javax.swing.JComboBox<String> jcbxEditarTipoEmpleado;
    public com.toedter.calendar.JDateChooser jdtcEditarFechaNacimiento;
    public javax.swing.JPasswordField jpswEditarConfirmarContraseña;
    public javax.swing.JPasswordField jpswEditarIngresarContraseña;
    public javax.swing.JTextField jtxtEditarApellidos;
    public javax.swing.JTextField jtxtEditarCorreo;
    public javax.swing.JTextField jtxtEditarDNI;
    public javax.swing.JTextField jtxtEditarNombres;
    public javax.swing.JTextField jtxtEditarNumCelular;
    // End of variables declaration//GEN-END:variables
}
