/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista_Jefe1;

/**
 *
 * @author admin
 */
public class Administrar_Tipo_Libro extends javax.swing.JInternalFrame {

    /**
     * Creates new form prueba
     */
    public Administrar_Tipo_Libro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlPestañaAdministrarTipoLibro = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblDatos_Tipo_Libro = new javax.swing.JTable();
        jlblRegistros_Tipo_Libro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtxtBuscarPorCodigoTipoLibro = new javax.swing.JTextField();
        jbtnAgregarTipoLibro = new javax.swing.JButton();
        jbtnEditarTipoLibro = new javax.swing.JButton();
        jbtnBuscarTipoLibro = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(null);
        setMaximumSize(new java.awt.Dimension(941, 526));
        setMinimumSize(new java.awt.Dimension(940, 526));
        setPreferredSize(new java.awt.Dimension(1121, 784));

        jpnlPestañaAdministrarTipoLibro.setBackground(new java.awt.Color(255, 255, 255));
        jpnlPestañaAdministrarTipoLibro.setMaximumSize(new java.awt.Dimension(941, 526));
        jpnlPestañaAdministrarTipoLibro.setMinimumSize(new java.awt.Dimension(940, 526));
        jpnlPestañaAdministrarTipoLibro.setPreferredSize(new java.awt.Dimension(1121, 784));
        jpnlPestañaAdministrarTipoLibro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 128, 128));
        jPanel2.setMinimumSize(new java.awt.Dimension(1090, 30));
        jPanel2.setPreferredSize(new java.awt.Dimension(1090, 30));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(30, 151, 196));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("REGISTRO DE TIPO DE LIBRO");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 30));

        jpnlPestañaAdministrarTipoLibro.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1090, 30));

        jtblDatos_Tipo_Libro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblDatos_Tipo_Libro);

        jpnlPestañaAdministrarTipoLibro.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 1080, 540));

        jlblRegistros_Tipo_Libro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblRegistros_Tipo_Libro.setForeground(new java.awt.Color(0, 0, 204));
        jlblRegistros_Tipo_Libro.setText("Numero de Registros: ");
        jlblRegistros_Tipo_Libro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnlPestañaAdministrarTipoLibro.add(jlblRegistros_Tipo_Libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 220, 40));

        jLabel1.setText("CODIGO");
        jpnlPestañaAdministrarTipoLibro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jpnlPestañaAdministrarTipoLibro.add(jtxtBuscarPorCodigoTipoLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 190, 30));

        jbtnAgregarTipoLibro.setText("Añadir");
        jbtnAgregarTipoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarTipoLibroActionPerformed(evt);
            }
        });
        jpnlPestañaAdministrarTipoLibro.add(jbtnAgregarTipoLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 80, 130, 40));

        jbtnEditarTipoLibro.setText("Editar");
        jpnlPestañaAdministrarTipoLibro.add(jbtnEditarTipoLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 120, 40));

        jbtnBuscarTipoLibro.setBackground(new java.awt.Color(153, 0, 0));
        jbtnBuscarTipoLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar 24x24.png"))); // NOI18N
        jpnlPestañaAdministrarTipoLibro.add(jbtnBuscarTipoLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 80, 70, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1121, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpnlPestañaAdministrarTipoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpnlPestañaAdministrarTipoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAgregarTipoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarTipoLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAgregarTipoLibroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtnAgregarTipoLibro;
    public javax.swing.JButton jbtnBuscarTipoLibro;
    public javax.swing.JButton jbtnEditarTipoLibro;
    public javax.swing.JLabel jlblRegistros_Tipo_Libro;
    public javax.swing.JPanel jpnlPestañaAdministrarTipoLibro;
    public javax.swing.JTable jtblDatos_Tipo_Libro;
    public javax.swing.JTextField jtxtBuscarPorCodigoTipoLibro;
    // End of variables declaration//GEN-END:variables
}
