/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Jefe1;


import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author admin
 */
public class AdministrarSuprema extends javax.swing.JFrame {

    /**
     * Creates new form AdministrarDatos
     */
    public AdministrarSuprema() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbtnAdministrarReporte = new javax.swing.JButton();
        jdesktoppnlContenedor = new javax.swing.JDesktopPane();
        jbtnCerrarSesion = new javax.swing.JButton();
        jbtnAdministrarEmpleados = new javax.swing.JButton();
        jbtnAdministrarAutores = new javax.swing.JButton();
        jbtnAdministrarEditoriales = new javax.swing.JButton();
        jbtnAdministrarTipoDeLibro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1270, 820));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pngwing.com (2) (1) (1) (1).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 110));

        jPanel1.setBackground(new java.awt.Color(0, 128, 128));
        jPanel1.setPreferredSize(new java.awt.Dimension(1265, 780));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnAdministrarReporte.setBackground(new java.awt.Color(0, 128, 128));
        jbtnAdministrarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reporte 35x35.png"))); // NOI18N
        jbtnAdministrarReporte.setText("Reporte");
        jbtnAdministrarReporte.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jbtnAdministrarReporte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnAdministrarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdministrarReporteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAdministrarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 140, 60));

        javax.swing.GroupLayout jdesktoppnlContenedorLayout = new javax.swing.GroupLayout(jdesktoppnlContenedor);
        jdesktoppnlContenedor.setLayout(jdesktoppnlContenedorLayout);
        jdesktoppnlContenedorLayout.setHorizontalGroup(
            jdesktoppnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1125, Short.MAX_VALUE)
        );
        jdesktoppnlContenedorLayout.setVerticalGroup(
            jdesktoppnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        jPanel1.add(jdesktoppnlContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 1125, 780));

        jbtnCerrarSesion.setBackground(new java.awt.Color(0, 128, 128));
        jbtnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar Sesion 28x32.png"))); // NOI18N
        jbtnCerrarSesion.setText("Cerrar Sesión");
        jbtnCerrarSesion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jbtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 140, 60));

        jbtnAdministrarEmpleados.setBackground(new java.awt.Color(0, 128, 128));
        jbtnAdministrarEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clientes 36x35.png"))); // NOI18N
        jbtnAdministrarEmpleados.setText("Adm. Empleados");
        jbtnAdministrarEmpleados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jbtnAdministrarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdministrarEmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAdministrarEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 140, 60));

        jbtnAdministrarAutores.setBackground(new java.awt.Color(0, 128, 128));
        jbtnAdministrarAutores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Autor 35x35.png"))); // NOI18N
        jbtnAdministrarAutores.setText("Adm. Autores");
        jbtnAdministrarAutores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jbtnAdministrarAutores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnAdministrarAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdministrarAutoresActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAdministrarAutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 140, 60));

        jbtnAdministrarEditoriales.setBackground(new java.awt.Color(0, 128, 128));
        jbtnAdministrarEditoriales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Editorial 35x35.png"))); // NOI18N
        jbtnAdministrarEditoriales.setText("Adm. Editoriales");
        jbtnAdministrarEditoriales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jbtnAdministrarEditoriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdministrarEditorialesActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAdministrarEditoriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 140, 60));

        jbtnAdministrarTipoDeLibro.setBackground(new java.awt.Color(0, 128, 128));
        jbtnAdministrarTipoDeLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Editorial 35x35.png"))); // NOI18N
        jbtnAdministrarTipoDeLibro.setText("Adm. Tipo Libro");
        jbtnAdministrarTipoDeLibro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jbtnAdministrarTipoDeLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdministrarTipoDeLibroActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAdministrarTipoDeLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 140, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1265, 780));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCerrarSesionActionPerformed

    private void jbtnAdministrarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdministrarReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAdministrarReporteActionPerformed

    private void jbtnAdministrarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdministrarEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAdministrarEmpleadosActionPerformed

    private void jbtnAdministrarAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdministrarAutoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAdministrarAutoresActionPerformed

    private void jbtnAdministrarTipoDeLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdministrarTipoDeLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAdministrarTipoDeLibroActionPerformed

    private void jbtnAdministrarEditorialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdministrarEditorialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAdministrarEditorialesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrarSuprema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrarSuprema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrarSuprema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrarSuprema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrarSuprema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbtnAdministrarAutores;
    public javax.swing.JButton jbtnAdministrarEditoriales;
    public javax.swing.JButton jbtnAdministrarEmpleados;
    public javax.swing.JButton jbtnAdministrarReporte;
    public javax.swing.JButton jbtnAdministrarTipoDeLibro;
    public javax.swing.JButton jbtnCerrarSesion;
    public javax.swing.JDesktopPane jdesktoppnlContenedor;
    // End of variables declaration//GEN-END:variables
}
