/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista_Jefe1;

/**
 *
 * @author admin
 */
public class Administrar_Editoriales extends javax.swing.JInternalFrame {

    /**
     * Creates new form prueba
     */
    public Administrar_Editoriales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlPestañaAdministrarUsuarios = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblDatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtxtBuscarPorDni = new javax.swing.JTextField();
        jbtnAgregarEmpleados = new javax.swing.JButton();
        jbtnEditarEmpleados = new javax.swing.JButton();
        jbtnBuscarEmpleados = new javax.swing.JButton();
        jlblRegistros = new javax.swing.JLabel();
        jbtnCancelarVuelo = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(null);

        jpnlPestañaAdministrarUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        jpnlPestañaAdministrarUsuarios.setPreferredSize(new java.awt.Dimension(930, 490));
        jpnlPestañaAdministrarUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 128, 128));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(30, 151, 196));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("REGISTRO DE EDITORIALES");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 850, 30));

        jpnlPestañaAdministrarUsuarios.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 910, 30));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jpnlPestañaAdministrarUsuarios.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 910, 10));

        jtblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblDatos);

        jpnlPestañaAdministrarUsuarios.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 900, 290));

        jLabel1.setText("CODIGO");
        jpnlPestañaAdministrarUsuarios.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jpnlPestañaAdministrarUsuarios.add(jtxtBuscarPorDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 30));

        jbtnAgregarEmpleados.setText("Añadir");
        jbtnAgregarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarEmpleadosActionPerformed(evt);
            }
        });
        jpnlPestañaAdministrarUsuarios.add(jbtnAgregarEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 100, 30));

        jbtnEditarEmpleados.setText("Editar");
        jpnlPestañaAdministrarUsuarios.add(jbtnEditarEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 100, 30));

        jbtnBuscarEmpleados.setText("Buscar");
        jpnlPestañaAdministrarUsuarios.add(jbtnBuscarEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 100, 30));

        jlblRegistros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblRegistros.setForeground(new java.awt.Color(0, 0, 204));
        jlblRegistros.setText("Numero de Registros: ");
        jlblRegistros.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnlPestañaAdministrarUsuarios.add(jlblRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 220, 40));

        jbtnCancelarVuelo.setBackground(new java.awt.Color(153, 0, 0));
        jbtnCancelarVuelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Tacho 20x24.png"))); // NOI18N
        jbtnCancelarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarVueloActionPerformed(evt);
            }
        });
        jpnlPestañaAdministrarUsuarios.add(jbtnCancelarVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 80, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpnlPestañaAdministrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpnlPestañaAdministrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAgregarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAgregarEmpleadosActionPerformed

    private void jbtnCancelarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCancelarVueloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtnAgregarEmpleados;
    public javax.swing.JButton jbtnBuscarEmpleados;
    public javax.swing.JButton jbtnCancelarVuelo;
    public javax.swing.JButton jbtnEditarEmpleados;
    public javax.swing.JLabel jlblRegistros;
    public javax.swing.JPanel jpnlPestañaAdministrarUsuarios;
    public javax.swing.JTable jtblDatos;
    public javax.swing.JTextField jtxtBuscarPorDni;
    // End of variables declaration//GEN-END:variables
}
