/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Jefe1;

/**
 *
 * @author User
 */
public class AgregarTipoLibro extends javax.swing.JFrame {

    /**
     * Creates new form AgregarAutor
     */
    public AgregarTipoLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtNombreTipoLibro = new javax.swing.JTextField();
        jbtnAgregarTipoLibro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbxDescuentoTpl = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jtxtPorcentajeDescuentoTpl = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Agregar tipo de libro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jtxtNombreTipoLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 220, 40));

        jbtnAgregarTipoLibro.setBackground(new java.awt.Color(51, 153, 255));
        jbtnAgregarTipoLibro.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jbtnAgregarTipoLibro.setText("Agregar");
        jbtnAgregarTipoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarTipoLibroActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAgregarTipoLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 130, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre del tipo de libro:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Descuento:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jcbxDescuentoTpl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VERDADERO", "FALSO" }));
        jPanel1.add(jcbxDescuentoTpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 220, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Porcentaje de Descuento:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));
        jPanel1.add(jtxtPorcentajeDescuentoTpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 220, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 380));
        jPanel1.getAccessibleContext().setAccessibleName("Agregar Tipo de Libro");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAgregarTipoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarTipoLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAgregarTipoLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarTipoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarTipoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarTipoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarTipoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarTipoLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbtnAgregarTipoLibro;
    public javax.swing.JComboBox<String> jcbxDescuentoTpl;
    public javax.swing.JTextField jtxtNombreTipoLibro;
    public javax.swing.JTextField jtxtPorcentajeDescuentoTpl;
    // End of variables declaration//GEN-END:variables
}
