/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Jefe1;

/**
 *
 * @author User
 */
public class EditarAutor extends javax.swing.JFrame {

    /**
     * Creates new form EditarAutor
     */
    public EditarAutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtEditarNombreAutor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcbxEstadoAutor = new javax.swing.JComboBox<>();
        jbtnActualizarAutor = new javax.swing.JButton();
        jcbxDescuento = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jtxtPorcentajeDescuento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Editar Autor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Estado:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));
        jPanel1.add(jtxtEditarNombreAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 220, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre del Autor:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jcbxEstadoAutor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));
        jcbxEstadoAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxEstadoAutorActionPerformed(evt);
            }
        });
        jPanel1.add(jcbxEstadoAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 220, 40));

        jbtnActualizarAutor.setBackground(new java.awt.Color(51, 153, 255));
        jbtnActualizarAutor.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jbtnActualizarAutor.setText("Actualizar");
        jPanel1.add(jbtnActualizarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 150, 50));

        jcbxDescuento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VERDADERO", "FALSO" }));
        jcbxDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxDescuentoActionPerformed(evt);
            }
        });
        jPanel1.add(jcbxDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 220, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Descuento:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));
        jPanel1.add(jtxtPorcentajeDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 220, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Porcentaje Descuento:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbxEstadoAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxEstadoAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbxEstadoAutorActionPerformed

    private void jcbxDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbxDescuentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarAutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbtnActualizarAutor;
    public javax.swing.JComboBox<String> jcbxDescuento;
    public javax.swing.JComboBox<String> jcbxEstadoAutor;
    public javax.swing.JTextField jtxtEditarNombreAutor;
    public javax.swing.JTextField jtxtPorcentajeDescuento;
    // End of variables declaration//GEN-END:variables
}
