/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Jefe1;

/**
 *
 * @author User
 */
public class EditarTipoLibro extends javax.swing.JFrame {

    /**
     * Creates new form EditarAutor
     */
    public EditarTipoLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtEditarTipoLibro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcbxEstadoTipoLibro = new javax.swing.JComboBox<>();
        jbtnActualizarTipoLibro = new javax.swing.JButton();
        jcbxDescuentoEditar = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jtxtPorcentajeDescuentoEditar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Editar Tipo de Libro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Estado:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));
        jPanel1.add(jtxtEditarTipoLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 220, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre del Tipo de Libro:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jcbxEstadoTipoLibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));
        jcbxEstadoTipoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxEstadoTipoLibroActionPerformed(evt);
            }
        });
        jPanel1.add(jcbxEstadoTipoLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 220, 40));

        jbtnActualizarTipoLibro.setBackground(new java.awt.Color(51, 153, 255));
        jbtnActualizarTipoLibro.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jbtnActualizarTipoLibro.setText("Actualizar");
        jPanel1.add(jbtnActualizarTipoLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 140, 50));

        jcbxDescuentoEditar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VERDADERO", "FALSO" }));
        jcbxDescuentoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxDescuentoEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jcbxDescuentoEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 220, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Descuento");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));
        jPanel1.add(jtxtPorcentajeDescuentoEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 220, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Porcentaje Descuento:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbxEstadoTipoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxEstadoTipoLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbxEstadoTipoLibroActionPerformed

    private void jcbxDescuentoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxDescuentoEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbxDescuentoEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarTipoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarTipoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarTipoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarTipoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarTipoLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbtnActualizarTipoLibro;
    public javax.swing.JComboBox<String> jcbxDescuentoEditar;
    public javax.swing.JComboBox<String> jcbxEstadoTipoLibro;
    public javax.swing.JTextField jtxtEditarTipoLibro;
    public javax.swing.JTextField jtxtPorcentajeDescuentoEditar;
    // End of variables declaration//GEN-END:variables
}
