/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Cliente;


import Vista_Empleado1.*;
import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author admin
 */
public class Principal_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form AdministrarDatos
     */
    public Principal_Cliente() {
        initComponents();    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpanelContenedorCliente = new javax.swing.JDesktopPane();
        jbtnRealizarCompra = new javax.swing.JButton();
        jbtnCerrarSesion = new javax.swing.JButton();
        jbtnActualizarDatos = new javax.swing.JButton();
        jbtnHistorial = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbtnLibrosPopulares = new javax.swing.JButton();
        jbtnRegistrarTarjeta = new javax.swing.JButton();
        jbtnPedidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 128, 128));
        jPanel1.setPreferredSize(getPreferredSize());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jpanelContenedorClienteLayout = new javax.swing.GroupLayout(jpanelContenedorCliente);
        jpanelContenedorCliente.setLayout(jpanelContenedorClienteLayout);
        jpanelContenedorClienteLayout.setHorizontalGroup(
            jpanelContenedorClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jpanelContenedorClienteLayout.setVerticalGroup(
            jpanelContenedorClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        jPanel1.add(jpanelContenedorCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 1120, 770));

        jbtnRealizarCompra.setBackground(new java.awt.Color(0, 128, 128));
        jbtnRealizarCompra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnRealizarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clientes 36x35.png"))); // NOI18N
        jbtnRealizarCompra.setText("Realizar Compra");
        jbtnRealizarCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jbtnRealizarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 140, 60));

        jbtnCerrarSesion.setBackground(new java.awt.Color(0, 128, 128));
        jbtnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar Sesion 28x32.png"))); // NOI18N
        jbtnCerrarSesion.setText("Cerrar Sesión");
        jPanel1.add(jbtnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 140, 60));

        jbtnActualizarDatos.setBackground(new java.awt.Color(0, 128, 128));
        jbtnActualizarDatos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnActualizarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ventas 35x35.png"))); // NOI18N
        jbtnActualizarDatos.setText("Actualizar Datos");
        jbtnActualizarDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jbtnActualizarDatos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jbtnActualizarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 140, 60));

        jbtnHistorial.setBackground(new java.awt.Color(0, 128, 128));
        jbtnHistorial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Libros 35x35.png"))); // NOI18N
        jbtnHistorial.setText("Historial");
        jbtnHistorial.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jbtnHistorial.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jbtnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 140, 60));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pngwing.com (2) (1) (1) (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 130));

        jbtnLibrosPopulares.setBackground(new java.awt.Color(0, 128, 128));
        jbtnLibrosPopulares.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnLibrosPopulares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RegistroC 24x30.png"))); // NOI18N
        jbtnLibrosPopulares.setText("Libros Populares");
        jbtnLibrosPopulares.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnLibrosPopulares.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jbtnLibrosPopulares.setMaximumSize(new java.awt.Dimension(110, 37));
        jbtnLibrosPopulares.setMinimumSize(new java.awt.Dimension(110, 37));
        jbtnLibrosPopulares.setPreferredSize(new java.awt.Dimension(110, 37));
        jbtnLibrosPopulares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLibrosPopularesActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnLibrosPopulares, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 140, 60));

        jbtnRegistrarTarjeta.setBackground(new java.awt.Color(0, 128, 128));
        jbtnRegistrarTarjeta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnRegistrarTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RegistroC 24x30.png"))); // NOI18N
        jbtnRegistrarTarjeta.setText("Registrar Tarjeta");
        jbtnRegistrarTarjeta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnRegistrarTarjeta.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jbtnRegistrarTarjeta.setMaximumSize(new java.awt.Dimension(110, 37));
        jbtnRegistrarTarjeta.setMinimumSize(new java.awt.Dimension(110, 37));
        jbtnRegistrarTarjeta.setPreferredSize(new java.awt.Dimension(110, 37));
        jbtnRegistrarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarTarjetaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnRegistrarTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 140, 60));

        jbtnPedidos.setBackground(new java.awt.Color(0, 128, 128));
        jbtnPedidos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RegistroC 24x30.png"))); // NOI18N
        jbtnPedidos.setText("Pedidos");
        jbtnPedidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnPedidos.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jbtnPedidos.setMaximumSize(new java.awt.Dimension(110, 37));
        jbtnPedidos.setMinimumSize(new java.awt.Dimension(110, 37));
        jbtnPedidos.setPreferredSize(new java.awt.Dimension(110, 37));
        jbtnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPedidosActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 140, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLibrosPopularesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLibrosPopularesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnLibrosPopularesActionPerformed

    private void jbtnRegistrarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnRegistrarTarjetaActionPerformed

    private void jbtnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbtnActualizarDatos;
    public javax.swing.JButton jbtnCerrarSesion;
    public javax.swing.JButton jbtnHistorial;
    public javax.swing.JButton jbtnLibrosPopulares;
    public javax.swing.JButton jbtnPedidos;
    public javax.swing.JButton jbtnRealizarCompra;
    public javax.swing.JButton jbtnRegistrarTarjeta;
    public javax.swing.JDesktopPane jpanelContenedorCliente;
    // End of variables declaration//GEN-END:variables
}
