/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista_Empleado1;

/**
 *
 * @author admin
 */
public class Admin_Libros extends javax.swing.JInternalFrame {

    /**
     * Creates new form Admin_Vuelos1
     */
    public Admin_Libros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlPestañaAdministrarVuelos = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jbtnAñadirLibroNuevo = new javax.swing.JButton();
        jbtnEditarLibro = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblTablaDeLibros = new javax.swing.JTable();
        jbtnAñadirLibroExistente = new javax.swing.JButton();
        jbtnBuscarLibro = new javax.swing.JButton();
        jlblRegistros_Libros = new javax.swing.JLabel();
        jspnConsultarPorIdLibro = new javax.swing.JSpinner();

        setPreferredSize(new java.awt.Dimension(1121, 784));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnlPestañaAdministrarVuelos.setBackground(new java.awt.Color(255, 255, 255));
        jpnlPestañaAdministrarVuelos.setMinimumSize(new java.awt.Dimension(930, 490));
        jpnlPestañaAdministrarVuelos.setPreferredSize(new java.awt.Dimension(930, 490));
        jpnlPestañaAdministrarVuelos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 128, 128));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(30, 151, 196));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("REGISTRO DE LIBROS");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 30));

        jpnlPestañaAdministrarVuelos.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1090, 30));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jpnlPestañaAdministrarVuelos.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 1090, 10));

        jbtnAñadirLibroNuevo.setText("Añadir Libro Nuevo");
        jpnlPestañaAdministrarVuelos.add(jbtnAñadirLibroNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 150, 40));

        jbtnEditarLibro.setText("Editar");
        jpnlPestañaAdministrarVuelos.add(jbtnEditarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, 110, 40));

        jLabel9.setText("ID DEL LIBRO");
        jpnlPestañaAdministrarVuelos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, -1));

        jtblTablaDeLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtblTablaDeLibros);

        jpnlPestañaAdministrarVuelos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 130, 1090, 560));

        jbtnAñadirLibroExistente.setText("Añadir Libro Existente");
        jpnlPestañaAdministrarVuelos.add(jbtnAñadirLibroExistente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 190, 40));

        jbtnBuscarLibro.setBackground(new java.awt.Color(153, 0, 0));
        jbtnBuscarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar 24x24.png"))); // NOI18N
        jpnlPestañaAdministrarVuelos.add(jbtnBuscarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 80, 60, 40));

        jlblRegistros_Libros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblRegistros_Libros.setForeground(new java.awt.Color(0, 0, 204));
        jlblRegistros_Libros.setText("Numero de Registros: ");
        jlblRegistros_Libros.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnlPestañaAdministrarVuelos.add(jlblRegistros_Libros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 695, 220, 40));
        jpnlPestañaAdministrarVuelos.add(jspnConsultarPorIdLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, 30));

        getContentPane().add(jpnlPestañaAdministrarVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton jbtnAñadirLibroExistente;
    public javax.swing.JButton jbtnAñadirLibroNuevo;
    public javax.swing.JButton jbtnBuscarLibro;
    public javax.swing.JButton jbtnEditarLibro;
    public javax.swing.JLabel jlblRegistros_Libros;
    private javax.swing.JPanel jpnlPestañaAdministrarVuelos;
    public javax.swing.JSpinner jspnConsultarPorIdLibro;
    public javax.swing.JTable jtblTablaDeLibros;
    // End of variables declaration//GEN-END:variables
}
