/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Empleado1;

/**
 *
 * @author User
 */
public class AñadirRegistroEmpresas extends javax.swing.JFrame {

    /**
     * Creates new form AñadirRegistroClientes
     */
    public AñadirRegistroEmpresas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtNombreEmpresa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtNumerodeIdentificacionEmpresa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtTelefonoEmpresa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtDireccionEmpresa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jdtcFechaCreacionEmpresa = new com.toedter.calendar.JDateChooser();
        jbtnRegistrarEmpresa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre de la Empresa");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, -1));
        jPanel1.add(jtxtNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 150, 40));

        jLabel3.setText("Numero de identificacion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        jPanel1.add(jtxtNumerodeIdentificacionEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, 40));

        jLabel4.setText("Telefono");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));
        jPanel1.add(jtxtTelefonoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 150, 40));

        jLabel5.setText("Direccion");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));
        jPanel1.add(jtxtDireccionEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 150, 40));

        jLabel6.setText("Fecha de Creacion");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jdtcFechaCreacionEmpresa.setDateFormatString("yyyy-MM-dd");
        jdtcFechaCreacionEmpresa.setMaxSelectableDate(new java.util.Date(253370786512000L));
        jdtcFechaCreacionEmpresa.setMinSelectableDate(new java.util.Date(-2208966572000L));
        jdtcFechaCreacionEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jdtcFechaCreacionEmpresaMousePressed(evt);
            }
        });
        jPanel1.add(jdtcFechaCreacionEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 150, 40));

        jbtnRegistrarEmpresa.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jbtnRegistrarEmpresa.setText("Registrar");
        jbtnRegistrarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarEmpresaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnRegistrarEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 250, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jdtcFechaCreacionEmpresaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdtcFechaCreacionEmpresaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdtcFechaCreacionEmpresaMousePressed

    private void jbtnRegistrarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarEmpresaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jbtnRegistrarEmpresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirRegistroEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirRegistroEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirRegistroEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirRegistroEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirRegistroEmpresas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbtnRegistrarEmpresa;
    public com.toedter.calendar.JDateChooser jdtcFechaCreacionEmpresa;
    public javax.swing.JTextField jtxtDireccionEmpresa;
    public javax.swing.JTextField jtxtNombreEmpresa;
    public javax.swing.JTextField jtxtNumerodeIdentificacionEmpresa;
    public javax.swing.JTextField jtxtTelefonoEmpresa;
    // End of variables declaration//GEN-END:variables
}
